name: Main
on:
- push
- pull_request_target
jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    env:
      CI: true
    steps:
    - uses: actions/checkout@master
    - run: make

    - uses: actions/setup-node@v2-beta
      with:
        node-version: 14.x

    - id: yarn-cache
      run: echo "::set-output name=directory::$(yarn cache dir)"
      working-directory: javascript

    - uses: actions/cache@v1
      with:
        path: ${{ steps.yarn-cache.outputs.directory }}
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-

    - name: Install node dependencies
      run: yarn install --frozen-lockfile
      working-directory: javascript

    - name: Test with jest
      run: yarn test
      working-directory: javascript

  automerge:
    name: AutoMerge
    needs: ci
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request_target' && (github.actor == github.repository_owner || github.actor == 'dependabot[bot]')
    steps:
    - uses: actions/github-script@v3
      with:
        script: |
          github.pulls.merge({
            owner: context.payload.repository.owner.login,
            repo: context.payload.repository.name,
            pull_number: context.payload.pull_request.number
          })
